name: Android Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup AVD and Run Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: bash scipts-for-ga.sh
      continue-on-error: true
        
    - name: Generate Test Report
      uses: dorny/test-reporter@v1.6.0
      with:
        name: results
        path: "**/report.xml" 
        reporter: java-junit
        fail-on-error: false


